version: 2

workflows:
  single-node:
    steps:
      -
        name: "single-node"
        command: experiment.run_single_node
        params:
          command: echo "Hello fromm Paperspace" 
          container: test-container
          machineType: "C3"
